services:
  mysql:
    container_name: mysql_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=wil.1234
      - MYSQL_DATABASE=messenger_clon_db
    ports:
      - '3306:3306'
    volumes:
      - data_app_volume:/var/lib/mysql

volumes:
  data_app_volume:
