services:
  messenger-app:
    build: .
    image: messenger_clon:v1
    ports:
      - '3000:3000'
    networks:
      - messenger_app_red
  postgres_db:
    container_name: messenger_db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=wil.1234
      - POSTGRES_DB=messenger_clon_db
    ports:
      - '5432:5432'
    volumes:
      - data_app_volume:/var/lib/postgresql/data
    networks:
      - messenger_app_red

volumes:
  data_app_volume:

networks:
  messenger_app_red:
